### PR TITLE
Fix deprecation warning

### PR DESCRIPTION
**Pull request by weshatheleopard**

### CODE REVIEW

**Comment by gleb** [comment]
Ruby 2.3?

**Comment by weshatheleopard** [comment]
Yep

**Comment by gleb** [comment]
Seems like a good change.  I wanted to reproduce the warning, but somehow I don't see it with 2.3.0. How do you trigger this warning?

**Comment by weshatheleopard** [comment]
Add to `~/Rakefile`:

```
Rake::TestTask.new(:test) do |t|
[...]
  t.warning = true
end
```

**Comment by gleb** [comment]
I've enabled warnings for assert_value builds too.  Any idea how t.warning = true got into your Rakefile?  Is this a new standard thing that Rails does, or your/company thing?

**Comment by weshatheleopard** [comment]
Don't remember how I came to know that flag, but it happened in the past 3 days :)

http://rake.rubyforge.org/classes/Rake/TestTask.html : 
[RW]    **warning** Request that the tests be run with the warning flag set. E.g. `warning=true` implies `ruby -w` used to run the tests.

**Comment by gleb** [comment]
Released in 1.5.3, thanks.

**Pull request closed without merging**
